kind: Namespace
apiVersion: v1
metadata:
  name: sam
  labels:
    name: sam
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-api
  namespace: sam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: math-api
  template:
    metadata:
      labels:
        app: math-api
    spec:
      containers:
        - name: math-api
          image: gcr.io/gke-playground-374709/maths-api@sha256:e8ae417d260cba841198da9b5ac95c6364ed5305436b552b04bd3e836198795e
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "math-api-service"
  namespace: "sam"
  labels:
    app: "math-api"
spec:
  ports:
   - port: 80
     targetPort: 5000
     name: http
  selector:
    app: "math-api"
  type: LoadBalancer
  loadBalancerIP: ""