kind: Namespace
apiVersion: v1
metadata:
  name: sam
  labels:
    name: sam
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: sam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - env:
        - name: SERVER_ADDR
          value: http://math-api-service:80
        - name: REQUESTS_PER_SECOND
          value: '10'
        image: gcr.io/gke-playground-374709/loadgenerator@sha256:0adb8e55008478d232a587c987303df316fe357cdd3b2389e8015e959556195c
        imagePullPolicy: Always
        name: main
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: loadgen-service
  namespace: sam
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: loadgenerator
  type: ClusterIP