apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-debugger
  namespace: sam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-debugger
  template:
    metadata:
      labels:
        app: ubuntu-debugger
    spec:
      containers:
        - name: ubuntu-debugger
          image: europe-west2-docker.pkg.dev/sams-sandbox-projects-12345/sams-registry/ubuntu-debugger:v0.0.2